slds-lmu/lecture_i2ml

03-performance/slides-resampling.Rnw
- Remove reference to spiral data.
- Add some minor clarifications.
Closes #296
=> Remove reference to spiral data.

01-intro/slides-intro.Rnw, 01-intro/slides-knn.Rnw, 01-intro/slides-limo.Rnw, 01-intro/slides-loss.Rnw, 01-intro/slides-tasks.Rnw, 02-classification/slides-classification-approaches.Rnw, 02-classification/slides-classification.Rnw, 02-classification/slides-logistic.Rnw, 03-performance/slides-measures.Rnw, 03-performance/slides-roc-2.Rnw, 03-performance/slides-train-test.Rnw, 04-trees/slides-cart1.Rnw, 04-trees/slides-cart2.Rnw, 04-trees/slides-forests1.Rnw, 05-tuning-nested/slides-nested-resampling.Rnw, style/setup.Rnw
=> Set the same seed for every chunk globally

Makefile, install.R
=> add option to install missing packages to makefile

slides/03-performance/perf_extra_stuff_unused.Rnw, slides/03-performance/slides-resampling.Rnw, slides/03-performance/slides-roc-2.Rnw, slides/03-performance/slides-train-test.Rnw, slides/forests/slides-forests-bagging.Rnw, slides/forests/slides-forests-featureimportance.Rnw, slides/forests/slides-forests-intro.Rnw, slides/ml-basics/slides-basics-datatask.Rnw, slides/ml-basics/slides-basics-learners.Rnw, slides/ml-basics/slides-basics-riskminimization.Rnw, slides/tuning/slides-nested-resampling.Rnw, slides/tuning/slides-tuning-intro.Rnw, slides/tuning/slides-tuning-tuningproblem.Rnw
I checked all the links linking to the figure sources on GDrive, and put the respective links in the .Rnw.
@fabian-s, you should have access to the figure folder on GDrive. I made the links sharable, such that people that have no access to the folder (e.g. Hiwis) can modify them, too.
=> Check links for figure sources; make them accessible 

exercises/day2/exercises/sol_logreg_decision_boundaries.Rnw
[solution_2.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/3946742/solution_2.pdf)
(reference #425 )
=> Improve ex day 2

code-demos/Makefile, code-demos/code_demo_cart.Rmd, code-demos/code_demo_randforests.Rmd
=> Improve code demos of day 4

_pkgdown.yml, vignettes/team.Rmd
=> Add license and contributing info to team page. See #404

exercises/day1/exercise_1.Rnw, exercises/day1/exercises/lm_knn_a_1.Rnw, exercises/day1/exercises/lm_knn_l_1a.R, exercises/day1/exercises/lrn_a_1.Rnw, exercises/day1/exercises/lrn_l_1.Rnw, exercises/day1/exercises/med_manh_a_1.Rnw, exercises/day1/exercises/med_manh_l_1.Rnw, exercises/day1/solution_1.Rnw, style/preamble_ueb.Rnw
[exercise_1.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4039458/exercise_1.pdf)
[solution_1.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4030877/solution_1.pdf)
(made bigger changes to the solution, since the argumentation became faulty/unprecise in the end IMO)
closes #411
=> Refactoring ex1 

exercises/day2/exercises/ex_mlr_decision_boundaries.Rnw, exercises/day2/exercises/ex_softmax.Rnw, exercises/day2/exercises/sol_mlr_decision_boundaries.R, exercises/day2/exercises/sol_naive_bayes.Rnw, exercises/day2/exercises/sol_softmax.Rnw, exercises/day2/solution_2.Rnw
Improve exercises 3 and 4
[solution_2.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/3979011/solution_2.pdf)
[exercise_2.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4096684/exercise_2.pdf)
reference #425
=> Refactoring ex2 tobi

exercises/day3/exercises/ROC_a_2.Rnw, exercises/day3/exercises/ROC_l_2.Rnw, exercises/day3/exercises/mlr_a_0.Rnw, exercises/day3/exercises/mlr_l_0.Rnw, exercises/day3/exercises/resampling_a_1.Rnw, exercises/day3/exercises/resampling_l_1.Rnw, exercises/day3/exercises/resampling_l_3.Rnw
[exercise_3.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4116965/exercise_3.pdf)
[solution_3.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4116964/solution_3.pdf)
=> Improve ex3

style/preamble_ueb.Rnw
=> Update exercise header

code-demos/code_demo_knn.Rmd, code-demos/code_demo_limo.Rmd, style/setup.Rmd
~~@fabian-s could you check if this compiles to pdf for you? I'm not sure why this does not compile on my machine.~~
=> Code demos day 1 mlr2 -> mlr3

code-demos/code_demo_cmpclass.Rmd, code-demos/code_demo_genclass.Rmd
=> Code demos day 2: mlr2 -> mlr3 

code-demos/code_demo_overfitting.Rmd, code-demos/code_demo_resampling.Rmd, code-demos/code_demo_roc.Rmd
=> mlr2 -> mlr3 code demos day 3

exercises/day5/exercises/kaggle_a_1.Rnw
=> Refactoring exercise 5

code-demos/code_demo_cmpclass.Rmd
Use the `multinom` learner for softmax regression instead of the `glmnet` *hack*. 
Closes #488
=> Switch softmax learner in compare-classifier-code demo

vignettes/get_demo_data.R
Fixes broken links to the code demos on the course page.
=> Fix code demo address on the course page (again)

vignettes/get_demo_data.R
=> Fix code demo url hopefully finally

code-demos/code-demos-order.txt
=> Add order file for code demos

slides/trees/slides-cart-intro.Rnw, slides/trees/slides-cart-treegrowing.Rnw
made changes in two lines of two different slides-  
1. CART-intro
2. CART-Tree-growing
=> Slide typos fixing 

_pkgdown.yml, vignettes/summer_school_course.Rmd
https://www.helmholtz-hida.de/en/activities/events/details/artikeldetail/helmholtz-virtual-ml-summer-school-2020/
=> Add summer school to website

slides/merger.R, slides/ml-basics/slides-order.txt
closes #547 
(we will not use auto-deploy since we want to run this script only for every release)
=> Auto full slideset

exercises/supervised-classification/exercises/ex_logreg_decision_boundaries.Rnw, exercises/supervised-classification/exercises/ex_softmax.Rnw, exercises/supervised-classification/exercises/sol_logreg_decision_boundaries.Rnw
=> unclear formulations on solution

slides/supervised-regression/slides-regression-losses.tex
=> Fix typo in slides slides-regression-losses.tex

exercises/evaluation/ex_rnw/ex_make_up_questions.Rnw
change to single-choice, and focus on eval
=> Small Changes IC week #7

slides/evaluation/slides-evaluation-generr.tex, slides/evaluation/slides-evaluation-measures-regression.tex, slides/evaluation/slides-evaluation-overfitting-underfitting.tex, slides/evaluation/slides-evaluation-resampling-1.tex, slides/evaluation/slides-evaluation-resampling-2.tex, slides/evaluation/slides-evaluation-test.tex, slides/evaluation/slides-evaluation-train.tex, slides/ml-basics/slides-basics-learner.tex
added new eval notation proposed for latex-math
=> added new notation

exercises/tuning-resampling/ex_rnw/ex_research_group_tuning-resampling.Rnw, exercises/usecase/ex_rnw/ex_usecase.Rnw, exercises/usecase/ic_usecase.Rnw
=> IC 12 usecase

exercises/Makefile, exercises/chapter.mk, exercises/evaluation/ex_rnw/ex_train-test.Rnw, exercises/evaluation/ex_rnw/sol_train-test.Rnw, exercises/forests/collection_forests.Rnw, exercises/forests/ex_rnw/ex_bagging.Rnw, exercises/forests/ex_rnw/sol_bagging.Rnw, exercises/gaussian-processes/Makefile, exercises/multiclass/sol_multiclass.Rnw, exercises/regularization/sol_regularization.Rnw, exercises/supervised-classification/ex_rnw/ex_logreg_dec_boundaries_enhanced.Rnw, exercises/svm/sol_svm.Rnw, exercises/testexam/Makefile, exercises/testexam/sol_testexam.Rnw, exercises/tuning-resampling/ex_rnw/ex_research_group_tuning-resampling.Rnw, exercises/tuning-resampling/ex_rnw/sol_research_group_tuning-resampling.Rnw, exercises/usecase/Makefile, style/preamble_ueb_coll.Rnw
calling make all will not trigger compilation if pdf is already present locally, so first force removal of existing pdfs and compile everything anew
=> exercise makefiles: remove all pdfs before make all

exercises/python-i2ml-requirements.txt
for Dependabot. No issues (I already used newer versions anyway).
=> security fixes

.github/workflows/pr-slide-check.yaml, style/beamerposter.sty, style/beamerthememlr.sty, style/customitemize.sty, style/frame2.sty, style/framei.sty, style/lmu-lecture.sty, style/preamble-cheatsheets.tex, style/preamble.tex, style/splitV.sty
This is experimental until new macros have been thoroughly tested.
=> Add new latex macros / envs
